openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: KOTO-rekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths:
  /api/oppija:
    get:
      tags:
        - "oppija-controller"
      summary: "Hakee listan kaikista oppijoista"
      operationId: "getOppijat"
      responses:
        200:
          description: "Oppijoiden hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
    post:
      tags:
        - "oppija-controller"
      summary: "Lisää oppijan järjestelmään"
      operationId: "addOppija"
      requestBody:
        description: "Lisättävän oppijan nimi"
        required: true
        content:
          "text/plain":
            schema:
              type: string
              example: "Etunimi Sukunimi"
      responses:
        201:
          description: "Oppijan lisäminen onnistui"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Oppija"
        400:
          description: "Virheellinen pyyntö"

  /api/kielitesti/user:
    get:
      tags:
        - "user-controller"
      summary: "Hakee listan Moodlen käyttäjistä"
      operationId: "getUsers"
      responses:
        200:
          description: "Käyttäjien hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
        503:
          description: "Käyttäjien haku Moodlesta epäonnistui"

  /api/oppijanumero:
    get:
      tags:
        - "oppijanumero-controller"
      summary: "Hakee yhden käyttäjän oppijanumerorekisteristä."
      operationId: "getOppijanumero"
      responses:
        200:
          description: "Oppija löytyi"
          content:
            "text/plain":
              schema:
                type: string
                example: "oid"
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Virheellinen pyyntö"

  # Mock API for YKI suoritukset
  /dev/yki/arvioijat:
    get:
      tags:
        - "yki-controller"
      summary: "Hakee YKI arvioijat"
      operationId: "getArvioijat"
      responses:
        200:
          description: "Arvioija tai arvioijia löytyi"
          content:
            "text/plain":
              schema:
                type: string

  # Mock API for YKI suoritukset
  /dev/yki/suoritukset:
    get:
      tags:
        - "yki-controller"
      summary: "Hakee YKI suoritukset"
      operationId: "getSuoritukset"
      parameters:
        - name: arvioitu
          in: query
          description: "Arviointi päivämäärä"
          required: false
          content:
            "text/plain":
              schema:
                type: string
                format: date

      responses:
        200:
          description: "Suoritus tai suorituksia löytyi"
          content:
            "text/plain":
              schema:
                type: string

  /dev/yki/trigger-schedule:
    get:
      tags:
        - "yki-controller"
      summary: "Ajaa YKI eräajon"
      operationId: "triggerSchedule"
      parameters:
        - name: lastSeen
          in: query
          required: false
          content:
            text/plain:
              schema:
                type: string
                format: date
      responses:
        "200":
          description: "Triggered"
        "500":
          description: "Failed"

components:
  schemas:
    # Domain: Oppija
    Oppija:
      required:
        - id
        - name
      title: Oppija
      description: KOTO-oppija
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
