openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: KOTO-rekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths:
  /api/oppijanumero:
    get:
      tags:
        - "oppijanumero-controller"
      summary: "Hakee yhden käyttäjän oppijanumerorekisteristä."
      operationId: "getOppijanumero"
      responses:
        200:
          description: "Oppija löytyi"
          content:
            "text/plain":
              schema:
                type: string
                example: "oid"
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Virheellinen pyyntö"

  # Mock API for YKI suoritukset
  /dev/yki/arvioijat:
    get:
      tags:
        - "yki-controller"
      summary: "Hakee YKI arvioijat"
      operationId: "getArvioijat"
      responses:
        200:
          description: "Arvioija tai arvioijia löytyi"
          content:
            "text/plain":
              schema:
                type: string

  # Mock API for YKI suoritukset
  /dev/yki/suoritukset:
    get:
      tags:
        - "yki-controller"
      summary: "Hakee YKI suoritukset"
      operationId: "getSuoritukset"
      parameters:
        - name: arvioitu
          in: query
          description: "Arviointi päivämäärä"
          required: false
          content:
            "text/plain":
              schema:
                type: string
                format: date

      responses:
        200:
          description: "Suoritus tai suorituksia löytyi"
          content:
            "text/plain":
              schema:
                type: string

  /dev/yki/trigger-schedule/yki-import-suoritukset:
    get:
      tags:
        - "yki-controller"
      summary: "Ajaa YKI eräajon"
      operationId: "triggerYkiImportSuoritukset"
      parameters:
        - name: dry-run
          in: header
          required: false
          schema:
            type: boolean
        - name: lastSeen
          in: query
          required: false
          content:
            text/plain:
              schema:
                type: string
                format: date
      responses:
        "200":
          description: "Triggered"
        "500":
          description: "Failed"
