openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: Kielitutkintorekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths:
  /yki/api/suoritukset/:
    get:
      tags:
        - "yki-controller"
      summary: "Palauttaa suoritukset CSV -formaatissa"
      parameters:
        - in: query
          name: includeVersionHistory
          schema:
            type: boolean
          required: false
          description: Sisällytetäänkö suorituksien versiohistoria CSV-tiedostoon
      operationId: getSuorituksetAsCsv
      responses:
        200:
          description: "Tietojen haku onnistui"
          content:
            "text/csv":
              schema:
                type: "string"
                format: binary
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Virhe palvelimella"
