openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: KOTO-rekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths:
  /api/oppija:
    get:
      tags:
        - "oppija-controller"
      summary: "Hakee listan kaikista oppijoista"
      operationId: "getOppijat"
      responses:
        200:
          description: "Oppijoiden hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
    post:
      tags:
        - "oppija-controller"
      summary: "Lisää oppijan järjestelmään"
      operationId: "addOppija"
      requestBody:
        description: "Lisättävän oppijan nimi"
        required: true
        content:
          "text/plain":
            schema:
              type: string
              example: "Etunimi Sukunimi"
      responses:
        201:
          description: "Oppijan lisäminen onnistui"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Oppija"
        400:
          description: "Virheellinen pyyntö"

  /api/kielitesti/user:
    get:
      tags:
        - "user-controller"
      summary: "Hakee listan Moodlen käyttäjistä"
      operationId: "getUsers"
      responses:
        200:
          description: "Käyttäjien hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
        503:
          description: "Käyttäjien haku Moodlesta epäonnistui"

  /api/oppijanumero:
    get:
      tags:
        - "oppijanumero-controller"
      summary: "Hakee yhden käyttäjän oppijanumerorekisteristä."
      operationId: "getOppijanumero"
      responses:
        200:
          description: "Oppija löytyi"
          content:
            "text/plain":
              schema:
                type: string
                example: "oid"
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Virheellinen pyyntö"

  /api/yki:
    get:
      tags:
        - "yki-controller"
      summary: "Hakee yhden käyttäjän YKI:n rajapinnasta"
      operationId: "getSuoritus"
      responses:
        200:
          description: "Suoritus löytyi"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/YkiSuoritus"
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Tapahtui odottamaton virhe"

components:
  schemas:
    # Domain: Oppija
    Oppija:
      required:
        - id
        - name
      title: Oppija
      description: KOTO-oppija
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    # Domain: YKI
    YkiSuoritus:
      type: object
      properties:
        nimi:
          type: string
          example: "Yrjö Ykittäjä"
        henkilötunnus:
          type: string
          example: "010106A911C"
        kansalaisuus:
          type: string
          example: "Yhdistynyt Kuningaskunta"
        sukupuoli:
          type: string
          example: "Muu"
        tutkinnonSuorittamispaikka:
          type: string
          example: "Taitotalo, Helsinki"
        tutkintokieli:
          type: string
          example: "suomi"
        saadutTaitotasoarviot:
          type: string
          example: "EVK B2/YKI 4"
        tutkintokertojenAjankohta:
          type: string
          example: "2024-09-27 12:40"
        tarpeellisetYhteystiedot:
          type: string
          example: "Yrjönkatu 13 C, 00120 Helsinki"
