openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: KOTO-rekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths:
  /api/oppija:
    get:
      tags:
        - "oppija-controller"
      summary: "Hakee listan kaikista oppijoista"
      operationId: "getOppijat"
      responses:
        200:
          description: "Oppijoiden hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
    post:
      tags:
        - "oppija-controller"
      summary: "Lisää oppijan järjestelmään"
      operationId: "addOppija"
      requestBody:
        description: "Lisättävän oppijan nimi"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Oppija"
      responses:
        201:
          description: "Oppijan lisäminen onnistui"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Oppija"
        400:
          description: "Virheellinen pyyntö"

  /api/kielitesti/user:
    get:
      tags:
        - "user-controller"
      summary: "Hakee listan Moodlen käyttäjistä"
      operationId: "getUsers"
      responses:
        200:
          description: "Käyttäjien hakeminen onnistui"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Oppija"
        503:
          description: "Käyttäjien haku Moodlesta epäonnistui"

  /api/oppijanumero:
    get:
      tags:
        - "oppijanumero-controller"
      summary: "Hakee yhden käyttäjän oppijanumerorekisteristä."
      operationId: "getOppijanumero"
      responses:
        200:
          description: "Oppija löytyi"
          content:
            "text/plain":
              schema:
                type: string
                example: "oid"
        400:
          description: "Virheellinen pyyntö"
        500:
          description: "Virheellinen pyyntö"

components:
  schemas:
    # Domain: Oppija
    Oppija:
      required:
        - firstName
        - lastName
        - oid
        - hetu
      title: Oppija
      description: KOTO-oppija
      type: object
      properties:
        id:
          type: integer
          format: int64
        oid:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        hetu:
          type: string
        nationality:
          type: string
        gender:
          type: string
        address:
          type: string
        postalCode:
          type: string
        city:
          type: string
        email:
          type: string

    # Domain: YKI
    YkiSuoritus:
      type: object
      properties:
        osallistuja:
          $ref: "#/components/schemas/YkiOsallistuja"
        jarjestajaOid:
          $ref: "#/components/schemas/YkiJarjestaja"

        # saadut taitotasoarviot
        tekstinYmmartamisenArvosana:
          $ref: "#/components/schemas/YkiArviointi"
        kirjoittamisenArvosana:
          $ref: "#/components/schemas/YkiArviointi"
        rakenteidenJaSanastonArvosana:
          $ref: "#/components/schemas/YkiArviointi"
        puheenYmmartamisenArvosana:
          $ref: "#/components/schemas/YkiArviointi"
        puhumisenArvosana:
          $ref: "#/components/schemas/YkiArviointi"
        yleistasoarvio:
          $ref: "#/components/schemas/YkiArviointi"

    YkiOsallistuja:
      type: object
      properties:
        oid:
          type: string
        sukunimi:
          type: string
          example: "Ykittäjä"
        etunimi:
          type: string
          example: "Yrjö"
        henkilotunnus:
          type: string
          example: "010106A911C"
          description: "Suomalainen henkilötunnus"
        kansalaisuus:
          type: string
          example: "GBR"
          minLength: 3
          maxLength: 3
        sukupuoli:
          type: string
          description: "N=Nainen, M=Mies, E=muu/ei ilmoiteta"
          example: "E"
          enum:
            - N
            - M
            - E

        # Tarpeelliset yhteystiedot
        katuosoite:
          type: string
          description: "Osallistujan tarpeellisten yhteystietojen katuosoite"
          example: "Hakaniemenranta 6"
        postinumero:
          type: string
          description: "Osallistujan tarpeellisten yhteystietojen postinumero"
          example: "00530"
          pattern: "^[0-9]{5}$"
        postitoimipaikka:
          type: string
          description: "Osallistujan tarpeellisten yhteystietojen postitoimipaikka"
          example: "Helsinki"
        sahköpostiosoite:
          type: string
          description: "Osallistujan tarpeellisten yhteystietojen sähköpostiosoite"
          example: "kirjaamo@oph.fi"
          format: "email"

    YkiJarjestaja:
      type: object
      properties:
        oid:
          type: string
          example: "1.2.246.562.24.01234567890"
          pattern: "^[0-9.]+$"
        nimi:
          type: string
          example: "Helsinki University"

    # Vastaa Soljen taulossa arviointi_suoritus
    YkiArviointi:
      type: object
      properties:
        arviointinumero:
          type: string
          example: "7/10"
        pvm:
          type: string
          example: "Päivämäärä, jolloin arviointi on tehty"
        tutkintokieli:
          type: string
          description: "ISO 639-3 - koodattu kieli, jota kielitutkinnossa testataan."
          example: "FIN"
          enum:
            - DEU
            - ENG
            - FIN
            - FRA
            - ITA
            - RUS
            - SME
            - SPA
            - SWE
        taso:
          type: string
          description: |
            Arvioitava taso.
            PT = perustaso. Vastaa CEFR A1/A2
            KT = keskitaso. Vastaa CEFR B1/B2
            YT = Ylin taso. Vastaa CEFR C1/C2
          example: "PT"
          enum:
            - "PT"
            - "KT"
            - "YT"
        arvioijaOid:
          type: string
          description: "Arvioijan OID-tunniste"
          example: "1.2.246.562.24.01234567890"
          pattern: "^[0-9.]+$"
