openapi: 3.0.0
info:
  version: 0.0.1
  title: kitu
tags:
  - name: kitu
    description: KOTO-rekisteri
servers:
  - url: http://localhost:8080
    description: Lokaali ympäristö
  - url: https://kios.untuvaopintopolku.fi
    description: Kehitysympäristö
  - url: https://kios.testiopintopolku.fi
    description: Testiympäristö
  - url: https://kios.opintopolku.fi
    description: Tuotantoympäristö
paths: {}
