# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: server
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: infra
    schedule:
      interval: weekly
    groups:
      cdk:
        patterns:
          - "aws-cdk*"
