receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  tail_sampling:
    policies:
      - name: health checks
        type: and
        and:
          and_sub_policy:
            - name: route-health-checks
              type: string_attribute
              string_attribute:
                key: http.route
                values: [ /actuator/health ]
            - name: probabilistic-policy
              type: probabilistic
              probabilistic:
                sampling_percentage: 0.1

extensions:
  health_check:

exporters:
  debug:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ tail_sampling, batch/traces ]
      exporters: [ debug, otlphttp/jaeger ]
    logs:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ debug ]

  extensions: [ health_check ]
