ALTER TABLE yki_arvioija
    ALTER COLUMN sukunimi SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN etunimet SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN sahkopostiosoite SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN katuosoite SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN postitoimipaikka SET DATA TYPE TEXT COLLATE "fi_FI"
;
ALTER TABLE yki_suoritus
    ALTER COLUMN sukunimi SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN etunimet SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN jarjestajan_nimi SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN etunimet SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN katuosoite SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN postitoimipaikka SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN email SET DATA TYPE TEXT COLLATE "fi_FI"
;
ALTER TABLE koto_suoritus
    ALTER COLUMN first_names SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN last_name SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN email SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN coursename SET DATA TYPE TEXT COLLATE "fi_FI"
;

ALTER TABLE vkt_suoritus
    ALTER COLUMN sukunimi SET DATA TYPE TEXT COLLATE "fi_FI",
    ALTER COLUMN etunimi SET DATA TYPE TEXT COLLATE "fi_FI"
;
