kitu.appUrl=https://kios.untuvaopintopolku.fi
kitu.opintopolkuHostname=virkailija.untuvaopintopolku.fi

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

kitu.kielitesti.wstoken=${KIELITESTI_TOKEN}
kitu.kielitesti.oppijanumerorekisteri.username=${OPPIJANUMEROREKISTERI_USERNAME}
kitu.kielitesti.oppijanumerorekisteri.password=${OPPIJANUMEROREKISTERI_PASSWORD}

