package fi.oph.kitu.random

val cefrLanguages = listOf("A1", "A2", "B1", "B2", "C1", "C2")
val cefrOptionalLanguages = listOf(null, "A1", "A2", "B1", "B2", "C1", "C2")

/** list of most popular 100 given female first name in Finland. */
@Suppress("ktlint:standard:argument-list-wrapping")
val femaleNames =
    listOf(
        "Aino", "Sofia", "Emma", "Ella", "Emilia", "Anna", "Maria", "Isla", "Aada", "Helmi", "Venla", "Anni",
        "Olivia", "Sara", "Julia", "Amanda", "Ellen", "Laura", "Aava", "Iida", "Lilja", "Aurora", "Siiri", "Lumi",
        "Lotta", "Veera", "Linnea", "Oona", "Mila", "Pihla", "Elsa", "Ronja", "Enni", "Vilma", "Emmi", "Milla",
        "Ilona", "Kerttu", "Minea", "Jenna-Maija", "Viivi", "Viola", "Sanni", "Nea", "Hilla", "Johanna", "Luna",
        "Alisa", "Jade", "Matilda", "Hanna", "Inka", "Nelli", "Alina", "Milja", "Elina", "Noora", "Bella", "Nella",
        "Minttu", "Seela", "Pinja", "Iina", "Jenni", "Ada", "Elle", "Enna", "Sanna", "Taika", "Alma", "Peppi",
        "Vanessa", "Adessa", "Minna", "Stella", "Eveliina", "Mari", "Fiona", "Roosa", "Suvi", "Heidi", "Iiris",
        "Jasmin", "Silja", "Adele", "Bea", "Elsi", "Saana", "Iisa", "Neela", "Liisa", "Satu", "Hilja", "Saara",
        "Aamu", "Henna", "Hilda", "Kukka", "Meri", "Fanni",
    )

/** list of the most popular 100 given male first names in Finland. */
@Suppress("ktlint:standard:argument-list-wrapping")
val maleNames =
    listOf(
        "Leo", "Elias", "Ville", "Eeli", "Oliver", "Noel", "Onni", "Eino", "Aleksi", "Eetu", "Leevi", "Pekka",
        "Matti", "Lauri", "Mikael", "Antti", "Mikko", "Matias", "Daniel", "Niilo", "Emil", "Joel", "Rasmus", "Niko",
        "Juhani", "Kalle", "Max", "Toivo", "Juho", "Eemil", "Alvar", "Jooa", "Hugo", "Julius", "Otto", "Olavi",
        "Väinö", "Eelis", "Vilho", "Mika", "Benjamin", "Anton", "Samuel", "Teemu", "Juha", "Luka", "Eemeli",
        "Oskari", "Juuso", "Timo", "Aapo", "Akseli", "Janne", "Valtteri", "Alex", "Aarni", "Miro", "Niklas", "Pyry",
        "Jonne", "Jesse", "Eliel", "Aaro", "Aatos", "Joonas", "Sisu", "Tuomas", "Viljami", "Jukka", "Sami", "Aaron",
        "Arttu", "Konsta", "Mio", "Roope", "Aatu", "Jaakko", "Kasper", "Marko", "Urho", "Jussi", "Lucas", "Lukas",
        "Otso", "Eero", "Olli", "Paavo", "Heikki", "Jere", "Miska", "Toni", "Ilmari", "Jari", "Topias", "Vili",
        "Valo", "Yrjö", "Jasper", "Markus", "Jani",
    )

@Suppress("ktlint:standard:argument-list-wrapping")
val surnames =
    listOf(
        "Korhonen", "Virtanen", "Mäkinen", "Nieminen", "Mäkelä", "Hämäläinen", "Laine", "Heikkinen", "Koskinen",
        "Järvinen", "Lehtonen", "Lehtinen", "Saarinen", "Salminen", "Heinonen", "Heikkilä", "Niemi", "Kinnunen",
        "Salonen", "Turunen", "Salo", "Laitinen", "Rantanen", "Tuominen", "Karjalainen", "Mattila", "Jokinen",
        "Savolainen", "Lahtinen", "Ahonen", "Ojala", "Leppänen", "Kallio", "Leinonen", "Väisänen", "Hiltunen",
        "Pitkänen", "Miettinen", "Manninen", "Aaltonen", "Koivisto", "Hakala", "Anttila", "Laaksonen", "Hirvonen",
        "Lehto", "Räsänen", "Laakso", "Toivonen", "Rantala", "Aalto", "Mustonen", "Niemelä", "Moilanen", "Nurmi",
        "Peltonen", "Seppälä", "Pulkkinen", "Hänninen", "Saari", "Kettunen", "Lappalainen", "Partanen", "Koskela",
        "Kemppainen", "Seppänen", "Kauppinen", "Ahola", "Salmi", "Lahti", "Aho", "Ikonen", "Huttunen", "Suominen",
        "Pesonen", "Halonen", "Kärkkäinen", "Nyman", "Mikkonen", "Johansson", "Koponen", "Peltola", "Lindholm",
        "Niskanen", "Oksanen", "Vainio", "Heiskanen", "Mikkola", "Koski", "Honkanen", "Immonen", "Harju",
        "Vuorinen", "Nurminen", "Määttä", "Kokkonen", "Rissanen", "Karppinen", "Mäki", "Heino", "Laukkanen",
        "Juntunen", "Rajala", "Rautiainen", "Kangas", "Keränen", "Jääskeläinen", "Parviainen", "Paananen",
        "Hartikainen", "Leino", "Mäenpää", "Karlsson", "Lindström", "Ruotsalainen", "Martikainen", "Uusitalo",
        "Hakkarainen", "Kokko", "Hyvärinen", "Laurila", "Toivanen", "Tikkanen", "Nevalainen", "Viitanen", "Salmela",
        "Makkonen", "Leskinen", "Nykänen", "Kuusisto", "Hietala", "Holopainen", "Häkkinen", "Andersson", "Ranta",
        "Tamminen", "Korpela", "Härkönen", "Eriksson", "Kukkonen", "Karhu", "Karvonen", "Hyvönen", "Tiainen",
        "Pasanen", "Jokela", "Jaakkola", "Saarela", "Sillanpää", "Väänänen", "Kosonen", "Malinen", "Kujala",
        "Rautio", "Virta", "Lindroos", "Autio", "Kivelä", "Timonen", "Lindqvist", "Jussila", "Kolehmainen", "Rinne",
        "Valtonen", "Hokkanen", "Huhtala", "Räisänen", "Lampinen", "Tolonen", "Nissinen", "Eskelinen", "Nousiainen",
        "Koivula", "Vartiainen", "Laakkonen", "Lindberg", "Lepistö", "Asikainen", "Kuusela", "Koistinen",
        "Kyllönen", "Luoma", "Pelkonen", "Kulmala", "Hautala", "Liimatainen", "Tolvanen", "Tuovinen", "Pietilä",
        "Helenius", "Penttinen", "Koivunen", "Voutilainen", "Huotari", "Viljanen", "Pennanen", "Marttila",
        "Riikonen", "Hyttinen", "Repo",
    )

var addresses =
    listOf(
        Triple("Rantatie", "Tampere", "33230"),
        Triple("Kirkkotie", "Turku", "20541"),
        Triple("Koulutie", "Lahti", "15550"),
        Triple("Teollisuustie", "Tampere", "33320"),
        Triple("Rinnetie", "Tampere", "33610"),
        Triple("Myllytie", "Helsinki", "00140"),
        Triple("Kuusitie", "Helsinki", "00270"),
        Triple("Rantalantie", "Turku", "21340"),
        Triple("Koivukuja", "Turku", "20720"),
        Triple("Peltotie", "Lahti", "15550"),
        Triple("Niementie", "Tampere", "34260"),
        Triple("Pajatie", "Lahti", "16100"),
        Triple("Vanhatie", "Vantaa", "01690"),
        Triple("Koivutie", "Lahti", "15550"),
        Triple("Riihitie", "Helsinki", "00330"),
        Triple("Koivulantie", "Tampere", "33800"),
        Triple("Pappilantie", "Espoo", "02770"),
        Triple("Aholantie", "Lahti", "15580"),
        Triple("Jokelantie", "Turku", "21340"),
        Triple("Peltolantie", "Helsinki", "00610"),
        Triple("Kuuselantie", "Lahti", "15540"),
        Triple("Opintie", "Turku", "20210"),
        Triple("Harjutie", "Lahti", "15561"),
        Triple("Oikotie", "Helsinki", "00140"),
        Triple("Hakatie", "Tampere", "33800"),
        Triple("Kalliotie", "Helsinki", "00770"),
        Triple("Rauhalantie", "Turku", "20240"),
        Triple("Taipaleentie", "Tampere", "33900"),
        Triple("Ojalantie", "Lahti", "16100"),
        Triple("Puistotie", "Helsinki", "00510"),
        Triple("Kangastie", "Helsinki", "00630"),
        Triple("Rajatie", "Vantaa", "01230"),
        Triple("Katajatie", "Lahti", "15550"),
        Triple("Harjuntie", "Kuopio", "70870"),
        Triple("Pihlajatie", "Helsinki", "00290"),
        Triple("Anttilantie", "Lahti", "15560"),
        Triple("Niittytie", "Lahti", "15550"),
        Triple("Honkatie", "Helsinki", "00290"),
        Triple("Kiviniementie", "Porvoo", "07130"),
        Triple("Asematie", "Vantaa", "01350"),
        Triple("Koivistontie", "Tampere", "33800"),
        Triple("Koskelantie", "Helsinki", "00600"),
        Triple("Pajutie", "Turku", "20880"),
        Triple("Hakalantie", "Viikki", "03320"),
        Triple("Koivuniementie", "Helsinki", "00890"),
        Triple("Urheilutie", "Lahti", "15550"),
        Triple("Rajalantie", "Nurmijärvi", "01900"),
        Triple("Rantakuja", "Espoo", "02170"),
        Triple("Metsolantie", "Helsinki", "00610"),
        Triple("Korpelantie", "Oulu", "90550"),
        Triple("Mattilantie", "Riihimäki", "11710"),
        Triple("Jokitie", "Helsinki", "00780"),
        Triple("Kanervatie", "Helsinki", "00730"),
        Triple("Alatie", "Lahti", "15560"),
        Triple("Keskustie", "Haapavesi", "92620"),
        Triple("Lehtolantie", "Vantaa", "01450"),
        Triple("Harjulantie", "Oulu", "90831"),
        Triple("Haapatie", "Helsinki", "00780"),
        Triple("Mikkolantie", "Helsinki", "00640"),
        Triple("Haapaniementie", "Kuopio", "70620"),
        Triple("Salmelantie", "Oulu", "90130"),
        Triple("Yhdystie", "Lahti", "15540"),
        Triple("Uutelantie", "Helsinki", "00995"),
        Triple("Toivolantie", "Lahti", "04600"),
        Triple("Koulukuja", "Oulu", "90831"),
        Triple("Linnankatu", "Mikkeli", "50100"),
        Triple("Korventie", "Turku", "21340"),
        Triple("Kotirannantie", "Tampere", "34240"),
        Triple("Koivurannantie", "Jyväskylä", "40400"),
        Triple("Ratakatu", "Rovaniemi", "96100"),
        Triple("Kivirannantie", "Tampere", "33870"),
        Triple("Mikonkatu", "Pori", "28100"),
        Triple("Vaasanpuistikko", "Vaasa", "65100"),
        Triple("Rantapolku", "Helsinki", "00330"),
        Triple("Kauppatie", "Lahti", "15550"),
    )

@Suppress("ktlint:standard:argument-list-wrapping")
val countryCodes =
    listOf(
        "ABW", "AFG", "AGO", "AIA", "ALA", "ALB", "AND", "ARE", "ARG", "ARM", "ASM", "ATA", "ATF", "ATG", "AUS", "AUT",
        "AZE", "BDI", "BEL", "BEN", "BES", "BFA", "BGD", "BGR", "BHR", "BHS", "BIH", "BLM", "BLR", "BLZ", "BMU", "BOL",
        "BRA", "BRB", "BRN", "BTN", "BVT", "BWA", "CAF", "CAN", "CCK", "CHE", "CHL", "CHN", "CIV", "CMR", "COD", "COG",
        "COK", "COL", "COM", "CPV", "CRI", "CUB", "CUW", "CXR", "CYM", "CYP", "CZE", "DEU", "DJI", "DMA", "DNK", "DOM",
        "DZA", "ECU", "EGY", "ERI", "ESH", "ESP", "EST", "ETH", "FIN", "FJI", "FLK", "FRA", "FRO", "FSM", "GAB", "GBR",
        "GEO", "GGY", "GHA", "GIB", "GIN", "GLP", "GMB", "GNB", "GNQ", "GRC", "GRD", "GRL", "GTM", "GUF", "GUM", "GUY",
        "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IMN", "IND", "IOT", "IRL", "IRN", "IRQ", "ISL", "ISR", "ITA",
        "JAM", "JEY", "JOR", "JPN", "KAZ", "KEN", "KGZ", "KHM", "KIR", "KNA", "KOR", "KWT", "LAO", "LBN", "LBR", "LBY",
        "LCA", "LIE", "LKA", "LSO", "LTU", "LUX", "LVA", "MAC", "MAF", "MAR", "MCO", "MDA", "MDG", "MDV", "MEX", "MHL",
        "MKD", "MLI", "MLT", "MMR", "MNE", "MNG", "MNP", "MOZ", "MRT", "MSR", "MTQ", "MUS", "MWI", "MYS", "MYT", "NAM",
        "NCL", "NER", "NFK", "NGA", "NIC", "NIU", "NLD", "NOR", "NPL", "NRU", "NZL", "OMN", "PAK", "PAN", "PCN", "PER",
        "PHL", "PLW", "PNG", "POL", "PRI", "PRK", "PRT", "PRY", "PSE", "PYF", "QAT", "REU", "ROU", "RUS", "RWA", "SAU",
        "SDN", "SEN", "SGP", "SGS", "SHN", "SJM", "SLB", "SLE", "SLV", "SMR", "SOM", "SPM", "SRB", "SSD", "STP", "SUR",
        "SVK", "SVN", "SWE", "SWZ", "SXM", "SYC", "SYR", "TCA", "TCD", "TGO", "THA", "TJK", "TKL", "TKM", "TLS", "TON",
        "TTO", "TUN", "TUR", "TUV", "TWN", "TZA", "UGA", "UKR", "UMI", "URY", "USA", "UZB", "VAT", "VCT", "VEN", "VGB",
        "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "ZAF", "ZMB", "ZWE",
    )
