CREATE DATABASE "kitu-dev" ENCODING 'UTF-8';
CREATE DATABASE "kitu-test" ENCODING 'UTF-8';

CREATE DATABASE "kitu-test-e2e-0" ENCODING 'UTF-8';
CREATE DATABASE "kitu-test-e2e-1" ENCODING 'UTF-8';
CREATE DATABASE "kitu-test-e2e-2" ENCODING 'UTF-8';
CREATE DATABASE "kitu-test-e2e-3" ENCODING 'UTF-8';
