name: Deploy

on:
  workflow_call:
    inputs:
      stacks:
        type: string
        default: "**"
      environment:
        type: string
      action:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Target environment
      action:
        type: choice
        options:
          - deploy
          - diff
        description: Action to perform
      stacks:
        type: string
        description: Stacks to deploy
        default: "**"

concurrency: deploy-${{ github.ref_name }}-${{ vars.account_id }}

env:
  TAG: ${{ github.sha }}

jobs:
  run:
    name: ${{ inputs.action }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.environment_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Log in to ${{ inputs.environment }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ vars.account_id }}:role/kitu-github-actions-role
      - name: Install dependencies
        run: npm ci
        working-directory: infra
      - name: ${{ inputs.action }}
        run: npx cdk ${{ inputs.action }} --require-approval=never --exclusively '${{ inputs.environment }}/${{ inputs.stacks }}'
        working-directory: infra
