name: Frontend Tests

on:
  workflow_call:

jobs:
  frontend_tests:
    name: Frontend tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start DB
        run: docker compose up -d db
        working-directory: server
      - name: Install dependencies
        run: npm ci
        working-directory: e2e
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: e2e
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
