name: Server Tests

on:
  workflow_call:

jobs:
  server_tests:
    name: Server tests
    runs-on: ubuntu-latest
    env:
      MISE_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: server
