name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_util:
    name: util
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: Util
      account_id: 961341524988

  deploy_dev:
    name: dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: Dev
      account_id: 682033502734

  deploy_test:
    name: test
    needs: deploy_dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: Test
      account_id: 961341546901

  deploy_prod:
    name: prod
    needs: deploy_test
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: Prod
      account_id: 515966535475
