name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency: build-${{ github.ref }}

jobs:
  deploy_dev:
    name: dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: dev
      account_id: 682033502734

  deploy_test:
    name: test
    needs: deploy_dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: test
      account_id: 961341546901

  deploy_prod:
    name: prod
    needs: deploy_test
    uses: ./.github/workflows/deploy-env.yml
    with:
      env: prod
      account_id: 515966535475
