name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  determine_action:
    runs-on: ubuntu-latest
    outputs:
      action: ${{ github.ref_name == 'main' && 'deploy' || 'diff' }}
    steps:
      - run: echo nothing to see here

  list_changes:
    name: List changes
    runs-on: ubuntu-latest
    outputs:
      mise: ${{ steps.filter.outputs.mise }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            mise:
              - '.mise.toml'
              - '.mise.*.toml'
            infra:
              - 'infra/**'

  update_tools_cache:
    name: Update tools cache if changed
    runs-on: ubuntu-latest
    needs: list_changes
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        if: needs.list_changes.outputs.mise == 'true'
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit_dependencies:
    name: Submit dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: update_tools_cache
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4.1.1
        with:
          directory: server
          ignore-maven-wrapper: "true"

  check_generated_sources:
    name: Check generated sources
    runs-on: ubuntu-latest
    needs: update_tools_cache
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate sources
        run: mvn generate-sources
        working-directory: server
      - name: Check for differences in generated sources
        run: git diff --exit-code

  server_tests:
    name: Server tests
    needs: update_tools_cache
    uses: ./.github/workflows/_server_tests.yml

  frontend_tests:
    name: Frontend tests
    uses: ./.github/workflows/_frontend_tests.yml
    needs: update_tools_cache

  lint:
    name: Check code formatting
    runs-on: ubuntu-latest
    needs: update_tools_cache
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        run: ./scripts/check-formatting.sh

  build_image:
    name: Build image
    uses: ./.github/workflows/_build_image.yml
    permissions:
      id-token: write
      contents: read
    needs:
      - check_generated_sources
      - server_tests
      - frontend_tests
      - lint

  deploy_util:
    name: Util
    uses: ./.github/workflows/_deploy-env.yml
    needs:
      - list_changes
      - update_tools_cache
      - determine_action
    if: needs.determine_action.outputs.action == 'deploy' || needs.list_changes.outputs.infra == 'true'
    with:
      environment: Util
      action: ${{ needs.determine_action.outputs.action }}

  deploy_dev:
    name: Dev
    needs:
      - build_image
      - determine_action
      - deploy_util
    uses: ./.github/workflows/_deploy-env.yml
    if: needs.determine_action.outputs.action == 'deploy' || needs.list_changes.outputs.infra == 'true'
    with:
      environment: Dev
      action: ${{ needs.determine_action.outputs.action }}

  deploy_test:
    name: Test
    needs:
      - determine_action
      - deploy_dev
    uses: ./.github/workflows/_deploy-env.yml
    if: needs.determine_action.outputs.action == 'deploy' || needs.list_changes.outputs.infra == 'true'
    with:
      environment: Test
      action: ${{ needs.determine_action.outputs.action }}

  deploy_prod:
    name: Prod
    needs:
      - determine_action
      - deploy_test
    uses: ./.github/workflows/_deploy-env.yml
    if: needs.determine_action.outputs.action == 'deploy' || needs.list_changes.outputs.infra == 'true'
    with:
      environment: Prod
      action: ${{ needs.determine_action.outputs.action }}
