name: Build

on:
  push:
    branches:
      - main
      - feat/cdk

concurrency: build-${{ github.ref }}

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - run: |
        tag=ghcr.io/opetushallitus/koto-rekisteri:$GITHUB_SHA
        docker build -t $tag . 
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push $tag
    - name: Log in to dev
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::682033502734:role/kitu-github-actions-role
    - name: Deploy
      run: |
        npm ci
        npx cdk deploy --all
      working-directory: infra
