name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  submit_dependencies:
    name: Submit dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4.1.1
        with:
          directory: server
          ignore-maven-wrapper: "true"

  check_generated_sources:
    name: Check generated sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Generate sources
        run: mvn generate-sources
        working-directory: server

      - name: Check for differences in generated sources
        run: git diff --exit-code

  build_image:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - deploy_util
      - check_generated_sources
      - submit_dependencies
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Log in to utility account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::961341524988:role/kitu-github-actions-role
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ steps.login-ecr.outputs.registry }}/kitu:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_util:
    name: util
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: Util
      action: ${{ github.ref_name == 'main' && 'deploy' || 'diff' }}

  deploy_dev:
    name: dev
    needs: build_image
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: Dev
      action: ${{ github.ref_name == 'main' && 'deploy' || 'diff' }}

  deploy_test:
    name: test
    needs: deploy_dev
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: Test
      action: ${{ github.ref_name == 'main' && 'deploy' || 'diff' }}

  deploy_prod:
    name: prod
    needs: deploy_test
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: Prod
      action: ${{ github.ref_name == 'main' && 'deploy' || 'diff' }}
