name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: "Check code formatting"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: Check formatting
        run: ./check-formatting.sh
