name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Start DB
        run: docker compose up -d db
        working-directory: server
      - name: Install dependencies
        run: npm ci
        working-directory: e2e
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: e2e
      - name: Build frontend
        run: (chmod +x ./scripts/build_frontend.sh && ./scripts/build_frontend.sh)
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
