name: Notify Slack

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.head_branch == 'main' && (github.event.workflow_run.conclusion == 'failure' || true)
    steps:
      - uses: actions/github-script@v7
        id: failed-jobs
        with:
          script: |
            const run = await octokit.rest.actions.listJobsForWorkflowRun({
              owner: "${{ github.event.workflow_run.head_repository.owner.login }}",
              repo: "${{ github.event.workflow_run.head_repository.name }}",
              run_id: "${{ github.event.workflow_run.id }}"
            })
            return ({
              failedJobs: run.jobs.filter(job => job.conclusion === "failure").map(job => job.html_url)
            })
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          errors: true
          payload: |
            name: "${{ github.event.workflow_run.name }}" 
            title: "${{ github.event.workflow_run.display_title }}"
            url: "${{ github.event.workflow_run.html_url }}"
            failed_jobs: "${{ join(steps.failed-jobs.outputs.failedJobs, ', ') }}"
