name: Notify Slack

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'failure' || true
    env:
      CONCLUSION: ${{ toJSON(github.event.workflow_run) }}
    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            name: "${{ github.event.workflow_run.name }}" 
            title: "${{ github.event.workflow_run.title }}"
            url: "${{ github.event.workflow_run.html_url }}"
