name: Notify Slack

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'failure'
    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          errors: true
          payload: |
            name: "${{ github.event.workflow_run.name }}" 
            title: "${{ github.event.workflow_run.display_title }}"
            url: "${{ github.event.workflow_run.html_url }}"
