name: Notify Slack

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'failure'
    env:
      CONCLUSION: ${{ toJSON(github.event.workflow_run) }}
    steps:
      - run: |
          echo "Conclusion: $CONCLUSION"
