# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:

  frotnend:
    name: "Build frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Build frontend
        run: |
          npm ci
          npm run build
          mkdir -p ../server/target/classes/
          mv out ../server/target/classes/static
        working-directory: ./frontend

  build:
    name: Run all tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Start DB
        run: docker compose up -d db
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: server
