name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: Run all tests

    runs-on: ubuntu-latest

    env:
      MISE_ENV: ci

    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Start DB
        run: docker compose up -d db
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: server
